### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by pyrothicc** [bk3a12/openvfd_enable_for_tx3_mini#1]
No issues, Would you be willing to help setup this on a tanix tx6, happy to pay thanks.

**Comment by bk3a12** [comment]
Hello,
Which OS is your box running? Do you have your own configuration file for openvfd? If not, please give me device tree blob for you current Android OS, maybe I can help.

**Comment by pyrothicc** [comment]
Do you have a discord or email i can contact you on i can send you Ssh details for the box which is running thanks.

**Comment by bk3a12** [comment]
Hello,
Please post the comments here. It will help other people who may be coming later.
No need to share ssh info.

**Comment by pyrothicc** [comment]
Okay thanks for you're reply.
Im using a Tanix TX6 and i have armbian installed on it i tried following you're installation guide 
but it throws errors up, i wasn't fully expecting it to just be plug and play but any help would be greatly appreciated.

Here's the version im running: Welcome to Debian GNU/Linux 11 (bullseye) with Linux 5.9.0-arm-64

I ran the kernal updates as explained by you, i then cloned the repo for the openvfd, and copied your makefile into mine.

Ran the command 
sudo ln -sf /boot/System.map-$(uname -r) /lib/modules/$(uname -r)/build/System.map.
Which worked fine then i tried to run 

make -j 4 

I ran this inside of the driver folder and get this error.


`root@arm-64:~/linux_openvfd/driver# make -j 4

make -C ../../../ M=/root/linux_openvfd/driver ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules

make[1]: Entering directory '/'

make[1]: *** No rule to make target 'modules'.  Stop.

make[1]: Leaving directory '/'

make: *** [Makefile:5: modules] Error 2

root@arm-64:~/linux_openvfd/driver#`


Thanks.

**Comment by bk3a12** [comment]
Hello,
Could you please check again the Makefile? Did you edit it as same as mine? I can see arguments ARCH and CROSS_COMPILE which are from original repository.

**Comment by pyrothicc** [comment]
Ah okay i had edited the makefile outside of the driver folder but had to edit it on the inside of the file, this is what the instructions stated 

make -j 4, modules_install all worked correctly and installed, I have checked lsmod and can see openvfd is running.

Run make OpenVFDService within linux_openvfd. Add executable priviledge by running chmod +x
im not sure how to add chmod +x to make it functional like that so if you could explain it'd be greatly appreciated 

I ran the command 
make OpenVFDService inside the linux_openvfd/ folder 
here's the contents of what it prints when i run
https://hastebin.com/epekanagoj.typescript

**Comment by bk3a12** [comment]
Hello, about the compilation log please consult with driver's author.
To add executive privilege, just run cmd: chmod +x OpenVFDService in terminal.

**Comment by pyrothicc** [comment]
hi @bk3a12 would the driver's author be arthur ? thanks.

**Comment by pyrothicc** [comment]
Hi @bk3a12 managed to get it to compile and run by the looks of things for the OpenVFDService part thanks to arthur.


Run make OpenVFDService within linux_openvfd. Add executable priviledge by running chmod +x
i wasn't able to add chmod +x since i had to run a specific command 


Modify your device tree source by adding openvfd item:
openvfd {
compatible = "open,vfd";
dev_name = "openvfd";
status = "okay";
}; \
Do you know where i can find this on armbian ? which specific area should i be looking in ?

**Comment by bk3a12** [comment]
Hello,
Please take a look at device tree source/device tree compiler (DTC)/device tree blob (DTB)
