### ISSUE TITLE
failed to create symbolic link '/lib/modules/5.9.0-arm-64/build/System.map': No such file or directory

### ISSUE THREAD

**Issue by Jeebus678** [bk3a12/openvfd_enable_for_tx3_mini#2]
root@arm-64:~# ln -sf /u-boot/System.map-$(uname -r) /lib/modules/$(uname -r)/build/System.map
ln: failed to create symbolic link '/lib/modules/5.9.0-arm-64/build/System.map': No such file or directory

I have a freshly installed version of armbian running on a tx3 mini, and it comes with no /lib/ file. Only a u-boot folder and u-boot.img file. I tried manually creating it, but that didn't work either.

**Comment by bk3a12** [comment]
Have you installed headers yet?
Why u-boot?
Try ln -sf /boot/System.map-$(uname -r) /lib/modules/$(uname -r)/build/System.map after that.

**Comment by Jeebus678** [comment]
I'm running armbian on a tv box, or more specifically the tx3 mini as written in the repo. I installed the full firmware build from armbian-config, but my filesystem is still fairly empty. I've also installed the headers from the link provided.

**Comment by Jeebus678** [comment]
Update: I had to install the armbian build [here](https://github.com/armbian/build) as well as the headers
